[project]
name = "snakemake-executor-plugin-slurm"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
ruff = ">=0.10.0,<0.11"
pytest = ">=9.0.3,<10"
coverage = ">=7.14.0,<8"
snakemake = ">=9.21.0,<10"

[feature.dev.pypi-dependencies]
snakemake-executor-plugin-slurm = { path = ".", editable = true }

[feature.conda_pkg.dependencies]
snakemake-executor-plugin-slurm = "==2.7.1"

[environments]
default = { features = ["dev"] }
conda-pkg = { features = ["conda_pkg"] }

[tasks]
format = "ruff format"
lint = "ruff check"
test = "coverage run -m pytest tests/ -sv --tb=short --disable-warnings"
coverage-report = "coverage report -m"