name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v6

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          environments: quality

      - name: Check formatting
        run: pixi run --environment quality format --check .

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v6

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          environments: quality

      - name: Check code
        run: pixi run --environment quality lint

  testing:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "8888:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v6

      - uses: koesterlab/setup-slurm-action@v1

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          environments: dev

      - name: Install plugin package
        run: pixi run --environment dev python -m pip install -e.

      - name: Run pytest
        run: pixi run --environment dev test

      - name: Run Coverage
        run: pixi run --environment dev coverage-report
