name: Post to Mastodon on PR Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  pull-requests: read

jobs:
  post_to_mastodon:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Post to Mastodon
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
                     curl -X POST -H "Authorization: Bearer ${{ secrets.MASTODON_ACCESS_TOKEN }}" \
                     -F "status=New release in Snakemake project '${{ github.event.repository.full_name }}' for pull request '#${{ github.event.pull_request.number }}' merged: '${{ github.event.pull_request.title }}'. Get the latest release from #Bioconda or #Pypi." \
                     https://fediscience.org/api/v1/statuses \
                     -w "\nResponse code: %{http_code}\n" \
                     -f || {
                       echo "Failed to post to Mastodon"
                       exit 1
                     }
