name: Post to Mastodon on PR Merge

on:
  push:
    branches:
      - main
    types:
      - closed

permissions:
  pull-requests: read

jobs:
  post_to_mastodon:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Post to Mastodon
        uses: actions/checkout@v4
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            export MASTODONBOT="${{ secrets.MASTODONBOT }}"
            export PR_TITLE="${{ github.event.release.tag_name }}"
            $GITHUB_WORKSPACE/post_to_mastodon.sh
