name: Post to Mastodon on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  post_to_mastodon:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Post to Mastodon
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: |
            export MASTODONBOT="${{ secrets.MASTODONBOT }}"
            export PR_TITLE="${{ github.event.release.tag_name }}"
            chmod +x $GITHUB_WORKSPACE/.github/workflows/post_to_mastodon.sh
            $GITHUB_WORKSPACE/.github/workflows/post_to_mastodon.sh
